### ISSUE TITLE
RWA loss for TimeSformer

### ISSUE THREAD

**Issue by vateye** [CuthbertCai/DemoVLP#1]
Hi, I am interested in the implementation of Frozen + RWA loss. Since the TimeSformer would generate a lot of patch, when calculating the RWA loss, the affinity matrix would be very large. Is there any hack to overcome this?

**Comment by CuthbertCai** [comment]
For now, when applying RWA loss to Frozen during pretraining, we usually only sample 1 frame from a video, and decrease the batchsize. When performing downstream tasks, we use `get_sim_by_segment` to decrease the GPU consumption.

 https://github.com/showlab/DemoVLP/blob/fc5a31d4b86517d4a9d2c873d30cdfade058ea0f/model/loss.py#L73
